%%cd /home/pawan/Work/Codes/gmg/gmg_c_new;
clear metis out;
[metis, out] = system(sprintf('./print_nd_perm %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s', matrix, ...
                                                    nc, ... 
                                                    wgt,  ...
                                                    opt_ptype, ...
                                                    opt_objtype, ...
                                                    opt_ctype, ...
                                                    opt_iptype, ...
                                                    opt_rtype, ...
                                                    opt_ncuts, ...
                                                    opt_nseps, ...
                                                    opt_num, ...
                                                    opt_niter, ...
                                                    opt_seed, ...
                                                    opt_minconn, ...
                                                    opt_contig, ...
                                                    opt_compress, ...
                                                    opt_ccorder, ...
                                                    opt_pfactor, ...
                                                    opt_ufactor, ...
                                                    opt_dbglvl, ...
                                                    opt_default ...
                                                    ));
                                                
 %system(sprintf('./print_part ~/Work/Matrices/matvf3DSKY50.mtx 20 0 0 0 0 0 0 1 1 0 10 0 0 1 0 0 0 0 0 1'))
 
 
